foreground              #D3C6AA
background              #1B2021
selection_foreground    #1B2021
selection_background    #D3C6AA

url_color               #7FBBB3

active_border_color     #A7C080
inactive_border_color   #232A2E
bell_border_color       #E67E80

active_tab_foreground   #1B2021
active_tab_background   #A7C080
inactive_tab_foreground #D3C6AA
inactive_tab_background #232A2E
tab_bar_background      #1B2021

color0 #232A2E
color1 #9E2A2B
color2  #A7C080
color3  #DBBC7F
color4  #7FBBB3
color5  #D699B6
color6  #83C092
color7  #D3C6AA
color8 #56635F
color9 #E67E80
color10 #A7C080
color11 #DBBC7F
color12 #7FBBB3
color13 #D699B6
color14 #83C092
color15 #F2E9E1

font_family                 Fira Code
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   11.0

background_opacity          0.7
dynamic_background_opacity  yes
allow_remote_control        yes

#window_padding_width        10
#tab_bar_min_tabs            1
#tab_bar_edge                bottom
#tab_bar_style               powerline
#tab_powerline_style         slanted
#tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}
