### OPTIONS ###

gfx-api = "Vulkan"

idle.minutes = 0

repeat-rate = { rate = 50, delay = 200 }
use-hardware-cursor = true
focus-follows-mouse = true
middle-click-paste = false

workspace-display-order = "sorted"

fallback-output-mode = "focus"

# Dark mode
on-startup = [
	{ type = "exec", exec = "gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'" },
	{ type = "exec", exec = "gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'" },
]

